# This file was generated by GoReleaser. DO NOT EDIT.
cask "burnless" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "661d5c92ce499da5846ec8f11e6ae89d0f27c05d29be3eff2aaba8adab3f1dc6"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de19f0af3fe6d65f5fce6eb1175f557aef2fd8fb951d5bc6993306231391e747"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d993217830ec8e35b23fcc7387f1c1796ae0dddea5c92a3f921cabbfd9e9c49b"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d97e3f8915035f7bfa0c1d0dd33f250512b455b696076fd636b88765e69a7c1c"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_linux_arm64.tar.gz"
    end
  end

  name "burnless"
  desc "Stop burning your error budget. Stop burning out your team. SRE config as code."
  homepage "https://github.com/Custos-com/Burnless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "burnless"

  # No zap stanza required

end
