# This file was generated by GoReleaser. DO NOT EDIT.
cask "burnless" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f102e28494e584d985366e4483ebad374918e195bf17e3ad8c5fcc9ee41c5067"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "370e70a9c6203aa1d8eda2761087e9b4e254f3e59f2a1f5a19aac4234baa06a5"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a8ae05920355f7315f07a59589545b6e1de11811e1395ae16e8fceb11f54cd4c"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1de354091eb306e1893eccd6609574b00661847c83aa6fb58fded9e02752ec2"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_linux_arm64.tar.gz"
    end
  end

  name "burnless"
  desc "Stop burning your error budget. Stop burning out your team. SRE config as code."
  homepage "https://github.com/Custos-com/Burnless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "burnless"

  # No zap stanza required

end
