# This file was generated by GoReleaser. DO NOT EDIT.
cask "burnless" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "45ef12d009c3ae608e0986a3351494492fb6a127af25eb0d4cfeefab80c36f84"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "200c6c327bd6e1a52242ae7d2f74e7b56b8e18745fdf8ef483ad9f575aee1494"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d79b6bbecd61a456bae3e60a362e8e88aaf909b93590c7ba16bba6da98aa2989"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b271e02299774e9bb8b4bc984fd24e4c78de9c4f7ea63f82767ab0579ea10ec2"
      url "https://github.com/Custos-com/Burnless/releases/download/v#{version}/burnless_linux_arm64.tar.gz"
    end
  end

  name "burnless"
  desc "Stop burning your error budget. Stop burning out your team. SRE config as code."
  homepage "https://github.com/Custos-com/Burnless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "burnless"

  # No zap stanza required

end
